-- Public, non-deceptive starter catalogue. Templates configure drafts only;
-- they never create approvals, tool credentials or production deployments.
BEGIN;

INSERT INTO workforce_templates (slug, name, department, summary, risk_level, autonomy_level, configuration)
VALUES
  ('ai-receptionist','AI Receptionist','Operations','Welcomes visitors, answers approved service questions and routes requests to the correct person.','medium',1,'{"functions":["Answer approved enquiries","Capture contact details","Route and escalate requests"],"skills":["Service triage","Clear communication","Information retrieval"],"human_review":"Sensitive, disputed and out-of-scope requests"}'),
  ('customer-service','Customer Service Colleague','Customer Experience','Resolves bounded service requests using approved policies and creates reviewable hand-offs.','medium',1,'{"functions":["Classify requests","Draft policy-grounded responses","Create escalation briefs"],"skills":["Customer support","Case summarisation","De-escalation"],"human_review":"Refunds, complaints and account changes"}'),
  ('sales-development','Sales Development Colleague','Sales','Qualifies consented leads and prepares personalised, reviewable outreach.','medium',1,'{"functions":["Research consented accounts","Qualify opportunities","Draft outreach"],"skills":["Qualification","CRM hygiene","Business writing"],"human_review":"All outbound messages and commercial commitments"}'),
  ('sales-assistant','Sales Assistant','Sales','Prepares meeting briefs, proposals and follow-ups from approved commercial information.','medium',1,'{"functions":["Prepare briefs","Draft proposals","Summarise meetings"],"skills":["Proposal writing","Pipeline support","Summarisation"],"human_review":"Pricing, promises and contract language"}'),
  ('hr-administrator','HR Administrator','People','Supports policy-grounded employee administration without making employment decisions.','high',1,'{"functions":["Answer policy questions","Prepare onboarding checklists","Route employee requests"],"skills":["HR operations","Document preparation","Privacy handling"],"human_review":"All employment decisions and sensitive cases"}'),
  ('recruitment-coordinator','Recruitment Coordinator','People','Coordinates interview logistics and candidate communications without scoring people.','high',1,'{"functions":["Coordinate interviews","Draft candidate updates","Prepare interview packs"],"skills":["Scheduling","Candidate communication","Process coordination"],"human_review":"Hiring decisions; appearance and emotion scoring are prohibited"}'),
  ('tutor','Learning Tutor','Learning','Explains approved learning material with citations and escalates safeguarding concerns.','medium',1,'{"functions":["Explain lessons","Generate practice questions","Cite approved sources"],"skills":["Tutoring","Adaptive explanation","Assessment support"],"human_review":"Assessments and safeguarding escalations"}'),
  ('learning-coach','Learning Coach','Learning','Supports learner planning, reflection and progress using approved curriculum boundaries.','medium',1,'{"functions":["Create study plans","Guide reflection","Summarise progress"],"skills":["Learning design","Coaching","Progress tracking"],"human_review":"Final assessment and pastoral decisions"}'),
  ('executive-assistant','Executive Assistant','Executive Office','Prepares schedules, briefs and action registers while protecting confidential material.','high',1,'{"functions":["Prepare daily briefs","Draft agendas","Track approved actions"],"skills":["Executive communication","Prioritisation","Meeting support"],"human_review":"Outbound commitments and confidential distribution"}'),
  ('operations-coordinator','Operations Coordinator','Operations','Monitors approved processes and prepares exception-based operational hand-offs.','medium',2,'{"functions":["Track workflow state","Prepare exception briefs","Coordinate hand-offs"],"skills":["Process monitoring","Operational reporting","Issue triage"],"human_review":"Exceptions affecting people, money or safety"}'),
  ('project-coordinator','Project Coordinator','Delivery','Maintains plans, action registers and reviewable project communications.','medium',1,'{"functions":["Update project plans","Track dependencies","Draft status reports"],"skills":["Project coordination","Risk logging","Status communication"],"human_review":"Scope, budget and deadline changes"}'),
  ('marketing-assistant','Marketing Assistant','Marketing','Creates evidence-grounded campaign drafts and content variations for review.','medium',1,'{"functions":["Draft campaign content","Repurpose approved material","Prepare content calendars"],"skills":["Copywriting","Content operations","Brand alignment"],"human_review":"Publication, claims and audience targeting"}'),
  ('social-media-coordinator','Social Media Coordinator','Marketing','Prepares platform-ready social drafts and routes reputational risks.','medium',1,'{"functions":["Draft social posts","Prepare response options","Tag review risks"],"skills":["Social writing","Community triage","Brand voice"],"human_review":"Publishing, complaints and crises"}'),
  ('finance-assistant','Finance Assistant','Finance','Prepares reconciliations and finance summaries without authorising transactions.','regulated',1,'{"functions":["Prepare reconciliations","Classify finance requests","Draft variance notes"],"skills":["Financial administration","Data checking","Reporting"],"human_review":"Payments, journals and financial advice"}'),
  ('accounting-clerk','Accounting Clerk','Finance','Organises source documents and prepares review queues for authorised accountants.','regulated',1,'{"functions":["Classify documents","Prepare posting batches","Flag exceptions"],"skills":["Bookkeeping support","Document validation","Exception detection"],"human_review":"Every posting and payment"}'),
  ('compliance-assistant','Compliance Assistant','Risk','Maps evidence to approved controls and prepares review-ready compliance packs.','regulated',1,'{"functions":["Collect evidence references","Map controls","Draft review packs"],"skills":["Control mapping","Evidence management","Policy retrieval"],"human_review":"All compliance determinations"}'),
  ('legal-intake','Legal Intake Colleague','Legal','Captures matter details and routes them without giving legal advice.','regulated',1,'{"functions":["Capture intake","Classify matter type","Prepare counsel brief"],"skills":["Legal operations","Issue spotting","Confidential handling"],"human_review":"All legal advice and decisions"}'),
  ('it-helpdesk','IT Helpdesk Colleague','Technology','Resolves approved low-risk support requests and creates traceable escalation tickets.','high',2,'{"functions":["Diagnose approved issues","Guide safe fixes","Create escalation tickets"],"skills":["Technical support","Troubleshooting","Ticket documentation"],"human_review":"Access changes, security incidents and destructive actions"}'),
  ('data-analyst','Data Analyst Colleague','Analytics','Produces reproducible summaries from approved, minimised datasets.','high',1,'{"functions":["Validate data inputs","Generate analysis","Document assumptions"],"skills":["Data analysis","Visualisation","Quality checking"],"human_review":"Decisions, sensitive joins and external reporting"}'),
  ('business-analyst','Business Analyst Colleague','Strategy','Structures requirements and prepares evidence-backed process recommendations.','medium',1,'{"functions":["Capture requirements","Map processes","Draft recommendations"],"skills":["Requirements analysis","Process mapping","Stakeholder synthesis"],"human_review":"Scope and operating changes"}'),
  ('procurement-assistant','Procurement Assistant','Procurement','Prepares comparable supplier information without selecting or committing suppliers.','high',1,'{"functions":["Prepare request packs","Compare approved criteria","Draft evaluation summaries"],"skills":["Procurement operations","Supplier research","Comparison"],"human_review":"Selection, negotiation and purchase commitments"}'),
  ('quality-assurance','Quality Assurance Colleague','Quality','Runs approved checks and prepares evidence for accountable release owners.','high',1,'{"functions":["Run quality checks","Record evidence","Prepare defect summaries"],"skills":["Quality testing","Evidence capture","Defect triage"],"human_review":"Risk acceptance and production release"}'),
  ('content-editor','Content Editor','Content','Checks approved content for clarity, consistency and accessibility.','medium',1,'{"functions":["Edit drafts","Check brand consistency","Flag unsupported claims"],"skills":["Editing","Accessibility","Fact checking"],"human_review":"Publication"}'),
  ('research-assistant','Research Assistant','Research','Finds and synthesises approved sources while labelling uncertainty and citations.','medium',1,'{"functions":["Search approved sources","Create evidence summaries","Maintain citations"],"skills":["Research","Source evaluation","Synthesis"],"human_review":"Material conclusions"}'),
  ('engineering-assistant','Engineering Assistant','Engineering','Prepares code, tests and documentation in a controlled review workflow.','high',1,'{"functions":["Draft code changes","Generate tests","Prepare technical notes"],"skills":["Software engineering","Testing","Documentation"],"human_review":"Every merge and production action"}')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  department = EXCLUDED.department,
  summary = EXCLUDED.summary,
  risk_level = EXCLUDED.risk_level,
  autonomy_level = EXCLUDED.autonomy_level,
  configuration = EXCLUDED.configuration,
  updated_at = now();

COMMIT;
