-- VowHumans commercial expansion (additive, MariaDB 10.6+/MySQL 8.0)
-- Apply after public/sql/001_adapter_schema.sql and 002_seed_reference_data.sql.
-- No DROP or destructive data conversion is performed. Test on staging and back up first.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS vhm_users (id CHAR(36) PRIMARY KEY,email VARCHAR(254) NOT NULL,email_verified_at DATETIME NULL,password_hash VARCHAR(255) NULL,status VARCHAR(32) NOT NULL DEFAULT 'invited',mfa_required TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_users_email(email));
CREATE TABLE IF NOT EXISTS vhm_workspaces (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,name VARCHAR(180) NOT NULL,slug VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',region_code VARCHAR(32) NULL,settings_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_workspace_slug(organisation_id,slug),KEY idx_vhm_workspace_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_departments (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,workspace_id CHAR(36) NULL,name VARCHAR(180) NOT NULL,cost_centre VARCHAR(80) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_departments_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_memberships (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,workspace_id CHAR(36) NULL,user_id CHAR(36) NOT NULL,role_code VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_membership(organisation_id,workspace_id,user_id),KEY idx_vhm_membership_user(user_id));
CREATE TABLE IF NOT EXISTS vhm_role_definitions (code VARCHAR(64) PRIMARY KEY,label VARCHAR(120) NOT NULL,permissions_json JSON NOT NULL,is_system TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vhm_auth_sessions (id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,token_hash CHAR(64) NOT NULL,ip_hash CHAR(64) NULL,user_agent_hash CHAR(64) NULL,expires_at DATETIME NOT NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_auth_token(token_hash),KEY idx_vhm_auth_user(user_id));
CREATE TABLE IF NOT EXISTS vhm_mfa_factors (id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,factor_type VARCHAR(32) NOT NULL,secret_ciphertext TEXT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',verified_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_mfa_user(user_id));
CREATE TABLE IF NOT EXISTS vhm_password_reset_tokens (id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,token_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_reset_token(token_hash));

CREATE TABLE IF NOT EXISTS vhm_voice_assets (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,identity_id CHAR(36) NULL,provider VARCHAR(80) NOT NULL,provider_ref VARCHAR(255) NULL,storage_key VARCHAR(512) NULL,licence_status VARCHAR(32) NOT NULL DEFAULT 'review',consent_id CHAR(36) NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_voice_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_face_assets (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,identity_id CHAR(36) NULL,storage_key VARCHAR(512) NOT NULL,sha256 CHAR(64) NOT NULL,consent_id CHAR(36) NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_face_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_identity_provenance (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,identity_id CHAR(36) NOT NULL,source_type VARCHAR(64) NOT NULL,source_reference VARCHAR(512) NULL,verification_status VARCHAR(32) NOT NULL DEFAULT 'pending',metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_provenance_identity(identity_id));
CREATE TABLE IF NOT EXISTS vhm_consent_events (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,consent_id CHAR(36) NOT NULL,event_type VARCHAR(40) NOT NULL,actor_id CHAR(36) NULL,evidence_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_consent_event(consent_id,created_at));
CREATE TABLE IF NOT EXISTS vhm_persona_objectives (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,persona_id CHAR(36) NOT NULL,objective_text TEXT NOT NULL,priority SMALLINT NOT NULL DEFAULT 100,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_objective_persona(persona_id));
CREATE TABLE IF NOT EXISTS vhm_persona_guardrails (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,persona_id CHAR(36) NOT NULL,rule_code VARCHAR(100) NOT NULL,rule_text TEXT NOT NULL,enforcement VARCHAR(32) NOT NULL DEFAULT 'prompt-and-policy',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_guardrail_persona(persona_id));
CREATE TABLE IF NOT EXISTS vhm_knowledge_bases (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,workspace_id CHAR(36) NULL,name VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',settings_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_kb_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_knowledge_chunks (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,document_id CHAR(36) NOT NULL,chunk_index INT NOT NULL,content_text MEDIUMTEXT NOT NULL,embedding_ref VARCHAR(512) NULL,metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_chunk(document_id,chunk_index));

CREATE TABLE IF NOT EXISTS vhm_session_participants (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,session_id CHAR(36) NOT NULL,participant_type VARCHAR(32) NOT NULL,subject_ref VARCHAR(255) NULL,joined_at DATETIME NULL,left_at DATETIME NULL,metadata_json JSON NULL,KEY idx_vhm_participant_session(session_id));
CREATE TABLE IF NOT EXISTS vhm_session_events (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,session_id CHAR(36) NOT NULL,event_type VARCHAR(80) NOT NULL,event_json JSON NULL,occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_session_event(session_id,occurred_at));
CREATE TABLE IF NOT EXISTS vhm_session_feedback (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,session_id CHAR(36) NOT NULL,rating SMALLINT NULL,comment_text TEXT NULL,consent_to_contact TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_feedback_session(session_id));
CREATE TABLE IF NOT EXISTS vhm_session_escalations (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,session_id CHAR(36) NOT NULL,reason_code VARCHAR(80) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'open',assigned_user_id CHAR(36) NULL,context_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_escalation_org(organisation_id,status));
CREATE TABLE IF NOT EXISTS vhm_recordings (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,session_id CHAR(36) NOT NULL,storage_key VARCHAR(512) NOT NULL,consent_id CHAR(36) NOT NULL,retention_until DATETIME NULL,status VARCHAR(32) NOT NULL DEFAULT 'processing',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_recording_session(session_id));

CREATE TABLE IF NOT EXISTS vhm_presenter_scenes (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,project_id CHAR(36) NOT NULL,scene_index INT NOT NULL,script_text MEDIUMTEXT NOT NULL,settings_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_scene(project_id,scene_index));
CREATE TABLE IF NOT EXISTS vhm_presenter_assets (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,project_id CHAR(36) NOT NULL,asset_type VARCHAR(64) NOT NULL,storage_key VARCHAR(512) NOT NULL,licence_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_asset_project(project_id));
CREATE TABLE IF NOT EXISTS vhm_render_jobs (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,project_id CHAR(36) NOT NULL,provider VARCHAR(80) NULL,status VARCHAR(32) NOT NULL DEFAULT 'queued',progress SMALLINT NOT NULL DEFAULT 0,input_json JSON NOT NULL,error_code VARCHAR(100) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_vhm_render_org(organisation_id,status));
CREATE TABLE IF NOT EXISTS vhm_render_outputs (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,render_job_id CHAR(36) NOT NULL,storage_key VARCHAR(512) NOT NULL,mime_type VARCHAR(120) NOT NULL,duration_ms INT NULL,sha256 CHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_output_job(render_job_id));
CREATE TABLE IF NOT EXISTS vhm_approvals (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,subject_type VARCHAR(64) NOT NULL,subject_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'requested',requested_by CHAR(36) NULL,decided_by CHAR(36) NULL,decision_note TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,decided_at DATETIME NULL,KEY idx_vhm_approval_subject(subject_type,subject_id));

CREATE TABLE IF NOT EXISTS vhm_integrations (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,slug VARCHAR(120) NOT NULL,name VARCHAR(180) NOT NULL,category VARCHAR(80) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'planned',auth_type VARCHAR(64) NOT NULL,scope_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_integration_slug(organisation_id,slug));
CREATE TABLE IF NOT EXISTS vhm_integration_installations (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,integration_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',credential_ref VARCHAR(255) NULL,settings_json JSON NULL,last_health_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_install_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_sync_jobs (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,installation_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'queued',cursor_ref VARCHAR(512) NULL,counts_json JSON NULL,error_code VARCHAR(100) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_sync_install(installation_id,status));
CREATE TABLE IF NOT EXISTS vhm_webhook_deliveries (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,webhook_id CHAR(36) NOT NULL,event_type VARCHAR(100) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'queued',attempt_count INT NOT NULL DEFAULT 0,next_attempt_at DATETIME NULL,response_code INT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_delivery_queue(status,next_attempt_at));

CREATE TABLE IF NOT EXISTS vhm_products (id CHAR(36) PRIMARY KEY,code VARCHAR(80) NOT NULL,name VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_product_code(code));
CREATE TABLE IF NOT EXISTS vhm_plans (id CHAR(36) PRIMARY KEY,code VARCHAR(80) NOT NULL,name VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',limits_json JSON NOT NULL,features_json JSON NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_plan_code(code));
CREATE TABLE IF NOT EXISTS vhm_prices (id CHAR(36) PRIMARY KEY,plan_id CHAR(36) NOT NULL,currency CHAR(3) NOT NULL,interval_code VARCHAR(20) NOT NULL,amount_minor BIGINT NULL,tax_inclusive TINYINT(1) NOT NULL DEFAULT 0,status VARCHAR(32) NOT NULL DEFAULT 'draft',valid_from DATETIME NULL,valid_until DATETIME NULL,KEY idx_vhm_price_plan(plan_id,currency));
CREATE TABLE IF NOT EXISTS vhm_subscriptions (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,plan_id CHAR(36) NOT NULL,provider VARCHAR(40) NOT NULL DEFAULT 'disabled',provider_ref VARCHAR(255) NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',current_period_start DATETIME NULL,current_period_end DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_subscription_org(organisation_id,status));
CREATE TABLE IF NOT EXISTS vhm_invoices (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,subscription_id CHAR(36) NULL,invoice_number VARCHAR(80) NOT NULL,currency CHAR(3) NOT NULL,total_minor BIGINT NOT NULL DEFAULT 0,tax_minor BIGINT NOT NULL DEFAULT 0,status VARCHAR(32) NOT NULL DEFAULT 'draft',issued_at DATETIME NULL,due_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_invoice_number(invoice_number));
CREATE TABLE IF NOT EXISTS vhm_payments (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,invoice_id CHAR(36) NULL,provider VARCHAR(40) NOT NULL,provider_ref VARCHAR(255) NULL,amount_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',idempotency_key VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_payment_idempotency(idempotency_key));
CREATE TABLE IF NOT EXISTS vhm_refunds (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,payment_id CHAR(36) NOT NULL,amount_minor BIGINT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'requested',reason_text TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_refund_payment(payment_id));
CREATE TABLE IF NOT EXISTS vhm_credit_transactions (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,amount_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,transaction_type VARCHAR(40) NOT NULL,reference_type VARCHAR(64) NULL,reference_id CHAR(36) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_credit_org(organisation_id,created_at));
CREATE TABLE IF NOT EXISTS vhm_budgets (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,workspace_id CHAR(36) NULL,period_code VARCHAR(32) NOT NULL,limit_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,alert_threshold SMALLINT NOT NULL DEFAULT 80,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_budget_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_billing_events (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,provider VARCHAR(40) NOT NULL,event_ref VARCHAR(255) NOT NULL,event_type VARCHAR(100) NOT NULL,payload_hash CHAR(64) NOT NULL,processed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_billing_event(provider,event_ref));

CREATE TABLE IF NOT EXISTS vhm_marketplace_publishers (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'application',display_name VARCHAR(180) NOT NULL,payout_provider_ref VARCHAR(255) NULL,reviewed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_publisher_org(organisation_id));
CREATE TABLE IF NOT EXISTS vhm_marketplace_items (id CHAR(36) PRIMARY KEY,publisher_id CHAR(36) NOT NULL,slug VARCHAR(180) NOT NULL,item_type VARCHAR(64) NOT NULL,name VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',description TEXT NULL,metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_market_item_slug(slug));
CREATE TABLE IF NOT EXISTS vhm_marketplace_versions (id CHAR(36) PRIMARY KEY,item_id CHAR(36) NOT NULL,version_code VARCHAR(40) NOT NULL,manifest_json JSON NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'review',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_market_version(item_id,version_code));
CREATE TABLE IF NOT EXISTS vhm_marketplace_orders (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',currency CHAR(3) NOT NULL,total_minor BIGINT NOT NULL,idempotency_key VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_market_order_key(idempotency_key));
CREATE TABLE IF NOT EXISTS vhm_marketplace_entitlements (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,item_id CHAR(36) NOT NULL,order_id CHAR(36) NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',starts_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,ends_at DATETIME NULL,UNIQUE KEY uq_vhm_entitlement(organisation_id,item_id));
CREATE TABLE IF NOT EXISTS vhm_marketplace_reviews (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,item_id CHAR(36) NOT NULL,user_id CHAR(36) NOT NULL,rating SMALLINT NOT NULL,review_text TEXT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_market_review(item_id,user_id));
CREATE TABLE IF NOT EXISTS vhm_marketplace_payouts (id CHAR(36) PRIMARY KEY,publisher_id CHAR(36) NOT NULL,period_code VARCHAR(32) NOT NULL,gross_minor BIGINT NOT NULL,commission_minor BIGINT NOT NULL,payout_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'held',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_payout_publisher(publisher_id,status));

CREATE TABLE IF NOT EXISTS vhm_partner_applications (id CHAR(36) PRIMARY KEY,organisation_name VARCHAR(180) NOT NULL,email VARCHAR(254) NOT NULL,partner_type VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'received',details_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_partner_application(status,created_at));
CREATE TABLE IF NOT EXISTS vhm_partners (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,partner_type VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',profile_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_partner_status(status));
CREATE TABLE IF NOT EXISTS vhm_partner_leads (id CHAR(36) PRIMARY KEY,partner_id CHAR(36) NOT NULL,lead_org_name VARCHAR(180) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'submitted',attribution_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_partner_lead(partner_id,status));
CREATE TABLE IF NOT EXISTS vhm_partner_commissions (id CHAR(36) PRIMARY KEY,partner_id CHAR(36) NOT NULL,reference_id CHAR(36) NOT NULL,amount_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_partner_commission(partner_id,status));

CREATE TABLE IF NOT EXISTS vhm_academy_courses (id CHAR(36) PRIMARY KEY,slug VARCHAR(180) NOT NULL,name VARCHAR(180) NOT NULL,level_code VARCHAR(40) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_course_slug(slug));
CREATE TABLE IF NOT EXISTS vhm_academy_lessons (id CHAR(36) PRIMARY KEY,course_id CHAR(36) NOT NULL,lesson_index INT NOT NULL,title VARCHAR(180) NOT NULL,content_ref VARCHAR(512) NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_lesson(course_id,lesson_index));
CREATE TABLE IF NOT EXISTS vhm_academy_enrolments (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,user_id CHAR(36) NOT NULL,course_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',enrolled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME NULL,UNIQUE KEY uq_vhm_enrolment(user_id,course_id));
CREATE TABLE IF NOT EXISTS vhm_academy_progress (id CHAR(36) PRIMARY KEY,enrolment_id CHAR(36) NOT NULL,lesson_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'started',score_percent DECIMAL(5,2) NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_progress(enrolment_id,lesson_id));
CREATE TABLE IF NOT EXISTS vhm_academy_certificates (id CHAR(36) PRIMARY KEY,enrolment_id CHAR(36) NOT NULL,verification_code VARCHAR(100) NOT NULL,issued_at DATETIME NOT NULL,revoked_at DATETIME NULL,metadata_json JSON NULL,UNIQUE KEY uq_vhm_certificate_code(verification_code));

CREATE TABLE IF NOT EXISTS vhm_notifications (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,user_id CHAR(36) NULL,channel VARCHAR(32) NOT NULL,template_code VARCHAR(100) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'queued',payload_json JSON NOT NULL,scheduled_at DATETIME NULL,sent_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_notification_queue(status,scheduled_at));
CREATE TABLE IF NOT EXISTS vhm_notification_preferences (id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,event_code VARCHAR(100) NOT NULL,channel VARCHAR(32) NOT NULL,enabled TINYINT(1) NOT NULL DEFAULT 1,UNIQUE KEY uq_vhm_notification_pref(user_id,event_code,channel));
CREATE TABLE IF NOT EXISTS vhm_sales_leads (id CHAR(36) PRIMARY KEY,lead_type VARCHAR(40) NOT NULL,email VARCHAR(254) NOT NULL,name VARCHAR(180) NULL,organisation_name VARCHAR(180) NULL,status VARCHAR(32) NOT NULL DEFAULT 'received',consent_at DATETIME NULL,details_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_sales_status(status,created_at));
CREATE TABLE IF NOT EXISTS vhm_support_tickets (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,user_id CHAR(36) NULL,email VARCHAR(254) NULL,priority VARCHAR(32) NOT NULL DEFAULT 'normal',status VARCHAR(32) NOT NULL DEFAULT 'open',subject VARCHAR(255) NOT NULL,description TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_support_status(status,priority));
CREATE TABLE IF NOT EXISTS vhm_content_entries (id CHAR(36) PRIMARY KEY,content_type VARCHAR(64) NOT NULL,slug VARCHAR(180) NOT NULL,locale VARCHAR(16) NOT NULL DEFAULT 'en-ZA',status VARCHAR(32) NOT NULL DEFAULT 'draft',title VARCHAR(255) NOT NULL,body_json JSON NOT NULL,published_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vhm_content_slug(content_type,slug,locale));
CREATE TABLE IF NOT EXISTS vhm_feature_flags (flag_key VARCHAR(120) PRIMARY KEY,enabled TINYINT(1) NOT NULL DEFAULT 0,scope_type VARCHAR(32) NOT NULL DEFAULT 'global',scope_id CHAR(36) NULL,metadata_json JSON NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vhm_analytics_events (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,workspace_id CHAR(36) NULL,event_type VARCHAR(100) NOT NULL,subject_type VARCHAR(64) NULL,subject_id CHAR(36) NULL,properties_json JSON NULL,occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vhm_analytics_org(organisation_id,occurred_at),KEY idx_vhm_analytics_type(event_type,occurred_at));
CREATE TABLE IF NOT EXISTS vhm_daily_metrics (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NOT NULL,metric_date DATE NOT NULL,metric_code VARCHAR(100) NOT NULL,value_decimal DECIMAL(20,4) NOT NULL DEFAULT 0,dimensions_json JSON NULL,UNIQUE KEY uq_vhm_daily_metric(organisation_id,metric_date,metric_code));
CREATE TABLE IF NOT EXISTS vhm_deletion_requests (id CHAR(36) PRIMARY KEY,organisation_id CHAR(36) NULL,user_id CHAR(36) NULL,subject_type VARCHAR(64) NOT NULL,subject_id CHAR(36) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'requested',legal_hold TINYINT(1) NOT NULL DEFAULT 0,requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME NULL,KEY idx_vhm_deletion_status(status,requested_at));
CREATE TABLE IF NOT EXISTS vhm_security_incidents (id CHAR(36) PRIMARY KEY,severity VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'open',title VARCHAR(255) NOT NULL,summary TEXT NULL,opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at DATETIME NULL,KEY idx_vhm_incident_status(status,severity));

INSERT IGNORE INTO vhm_role_definitions(code,label,permissions_json,is_system) VALUES
('owner','Owner',JSON_ARRAY('organisation:manage','billing:manage','audit:read'),1),
('org_admin','Organisation admin',JSON_ARRAY('organisation:manage','human:create','persona:publish'),1),
('creator','Creator',JSON_ARRAY('human:create'),1),
('developer','Developer',JSON_ARRAY('api-keys:manage','sessions:read-metadata'),1),
('security_reviewer','Security reviewer',JSON_ARRAY('security:review','audit:read'),1),
('viewer','Viewer',JSON_ARRAY(),1);

INSERT IGNORE INTO vhm_feature_flags(flag_key,enabled) VALUES
('ENABLE_LIVE_SESSIONS',0),('ENABLE_LIVEKIT',0),('ENABLE_MARKETPLACE_PURCHASES',0),('ENABLE_MARKETPLACE_PAYOUTS',0),('ENABLE_PAYFAST',0),('ENABLE_STRIPE',0),('ENABLE_ENTERPRISE_SSO',0),('ENABLE_TRANSCRIPTS',0),('ENABLE_RECORDINGS',0),('ENABLE_INVESTOR_DATA_ROOM',0);
