-- Governed starter catalogue. Templates create drafts only and never approve,
-- deploy, execute tools or create provider credentials.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

INSERT INTO vhm_workforce_templates(id,slug,name,department,summary,risk_level,autonomy_level,configuration_json,status) VALUES
('91000000-0000-4000-8000-000000000001','ai-receptionist','AI Receptionist','Operations','Welcomes visitors, answers approved service questions and routes requests.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Answer approved enquiries','Capture contact details','Route and escalate requests'),'skills',JSON_ARRAY('Service triage','Clear communication','Information retrieval'),'human_review','Sensitive, disputed and out-of-scope requests'),'published'),
('91000000-0000-4000-8000-000000000002','customer-service','Customer Service Colleague','Customer Experience','Resolves bounded service requests using approved policies and reviewable hand-offs.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Classify requests','Draft policy-grounded responses','Create escalation briefs'),'skills',JSON_ARRAY('Customer support','Case summarisation','De-escalation'),'human_review','Refunds, complaints and account changes'),'published'),
('91000000-0000-4000-8000-000000000003','sales-development','Sales Development Colleague','Sales','Qualifies consented leads and prepares reviewable outreach.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Research consented accounts','Qualify opportunities','Draft outreach'),'skills',JSON_ARRAY('Qualification','CRM hygiene','Business writing'),'human_review','All outbound messages and commercial commitments'),'published'),
('91000000-0000-4000-8000-000000000004','sales-assistant','Sales Assistant','Sales','Prepares meeting briefs, proposals and follow-ups from approved information.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Prepare briefs','Draft proposals','Summarise meetings'),'skills',JSON_ARRAY('Proposal writing','Pipeline support','Summarisation'),'human_review','Pricing, promises and contract language'),'published'),
('91000000-0000-4000-8000-000000000005','hr-administrator','HR Administrator','People','Supports policy-grounded employee administration without making employment decisions.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Answer policy questions','Prepare onboarding checklists','Route employee requests'),'skills',JSON_ARRAY('HR operations','Document preparation','Privacy handling'),'human_review','All employment decisions and sensitive cases'),'published'),
('91000000-0000-4000-8000-000000000006','recruitment-coordinator','Recruitment Coordinator','People','Coordinates interviews without scoring people.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Coordinate interviews','Draft candidate updates','Prepare interview packs'),'skills',JSON_ARRAY('Scheduling','Candidate communication','Process coordination'),'human_review','Hiring decisions; appearance and emotion scoring are prohibited'),'published'),
('91000000-0000-4000-8000-000000000007','tutor','Learning Tutor','Learning','Explains approved learning material with citations.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Explain lessons','Generate practice questions','Cite approved sources'),'skills',JSON_ARRAY('Tutoring','Adaptive explanation','Assessment support'),'human_review','Assessments and safeguarding escalations'),'published'),
('91000000-0000-4000-8000-000000000008','learning-coach','Learning Coach','Learning','Supports learner planning and progress within curriculum boundaries.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Create study plans','Guide reflection','Summarise progress'),'skills',JSON_ARRAY('Learning design','Coaching','Progress tracking'),'human_review','Final assessment and pastoral decisions'),'published'),
('91000000-0000-4000-8000-000000000009','executive-assistant','Executive Assistant','Executive Office','Prepares schedules, briefs and action registers.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Prepare daily briefs','Draft agendas','Track approved actions'),'skills',JSON_ARRAY('Executive communication','Prioritisation','Meeting support'),'human_review','Outbound commitments and confidential distribution'),'published'),
('91000000-0000-4000-8000-000000000010','operations-coordinator','Operations Coordinator','Operations','Monitors approved processes and prepares exception hand-offs.','medium',2,JSON_OBJECT('functions',JSON_ARRAY('Track workflow state','Prepare exception briefs','Coordinate hand-offs'),'skills',JSON_ARRAY('Process monitoring','Operational reporting','Issue triage'),'human_review','Exceptions affecting people, money or safety'),'published'),
('91000000-0000-4000-8000-000000000011','project-coordinator','Project Coordinator','Delivery','Maintains plans, actions and reviewable project communications.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Update project plans','Track dependencies','Draft status reports'),'skills',JSON_ARRAY('Project coordination','Risk logging','Status communication'),'human_review','Scope, budget and deadline changes'),'published'),
('91000000-0000-4000-8000-000000000012','marketing-assistant','Marketing Assistant','Marketing','Creates evidence-grounded campaign drafts.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Draft campaign content','Repurpose approved material','Prepare content calendars'),'skills',JSON_ARRAY('Copywriting','Content operations','Brand alignment'),'human_review','Publication, claims and audience targeting'),'published'),
('91000000-0000-4000-8000-000000000013','social-media-coordinator','Social Media Coordinator','Marketing','Prepares platform-ready social drafts and routes reputational risks.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Draft social posts','Prepare response options','Tag review risks'),'skills',JSON_ARRAY('Social writing','Community triage','Brand voice'),'human_review','Publishing, complaints and crises'),'published'),
('91000000-0000-4000-8000-000000000014','finance-assistant','Finance Assistant','Finance','Prepares reconciliations without authorising transactions.','regulated',1,JSON_OBJECT('functions',JSON_ARRAY('Prepare reconciliations','Classify finance requests','Draft variance notes'),'skills',JSON_ARRAY('Financial administration','Data checking','Reporting'),'human_review','Payments, journals and financial advice'),'published'),
('91000000-0000-4000-8000-000000000015','accounting-clerk','Accounting Clerk','Finance','Organises source documents for authorised accountants.','regulated',1,JSON_OBJECT('functions',JSON_ARRAY('Classify documents','Prepare posting batches','Flag exceptions'),'skills',JSON_ARRAY('Bookkeeping support','Document validation','Exception detection'),'human_review','Every posting and payment'),'published'),
('91000000-0000-4000-8000-000000000016','compliance-assistant','Compliance Assistant','Risk','Maps evidence to controls and prepares compliance packs.','regulated',1,JSON_OBJECT('functions',JSON_ARRAY('Collect evidence references','Map controls','Draft review packs'),'skills',JSON_ARRAY('Control mapping','Evidence management','Policy retrieval'),'human_review','All compliance determinations'),'published'),
('91000000-0000-4000-8000-000000000017','legal-intake','Legal Intake Colleague','Legal','Captures matters without giving legal advice.','regulated',1,JSON_OBJECT('functions',JSON_ARRAY('Capture intake','Classify matter type','Prepare counsel brief'),'skills',JSON_ARRAY('Legal operations','Issue spotting','Confidential handling'),'human_review','All legal advice and decisions'),'published'),
('91000000-0000-4000-8000-000000000018','it-helpdesk','IT Helpdesk Colleague','Technology','Resolves approved low-risk support requests.','high',2,JSON_OBJECT('functions',JSON_ARRAY('Diagnose approved issues','Guide safe fixes','Create escalation tickets'),'skills',JSON_ARRAY('Technical support','Troubleshooting','Ticket documentation'),'human_review','Access changes, security incidents and destructive actions'),'published'),
('91000000-0000-4000-8000-000000000019','data-analyst','Data Analyst Colleague','Analytics','Produces reproducible summaries from approved datasets.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Validate data inputs','Generate analysis','Document assumptions'),'skills',JSON_ARRAY('Data analysis','Visualisation','Quality checking'),'human_review','Decisions, sensitive joins and external reporting'),'published'),
('91000000-0000-4000-8000-000000000020','business-analyst','Business Analyst Colleague','Strategy','Structures requirements and evidence-backed recommendations.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Capture requirements','Map processes','Draft recommendations'),'skills',JSON_ARRAY('Requirements analysis','Process mapping','Stakeholder synthesis'),'human_review','Scope and operating changes'),'published'),
('91000000-0000-4000-8000-000000000021','procurement-assistant','Procurement Assistant','Procurement','Prepares supplier comparisons without making commitments.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Prepare request packs','Compare approved criteria','Draft evaluation summaries'),'skills',JSON_ARRAY('Procurement operations','Supplier research','Comparison'),'human_review','Selection, negotiation and purchase commitments'),'published'),
('91000000-0000-4000-8000-000000000022','quality-assurance','Quality Assurance Colleague','Quality','Runs approved checks and prepares evidence for release owners.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Run quality checks','Record evidence','Prepare defect summaries'),'skills',JSON_ARRAY('Quality testing','Evidence capture','Defect triage'),'human_review','Risk acceptance and production release'),'published'),
('91000000-0000-4000-8000-000000000023','content-editor','Content Editor','Content','Checks approved content for clarity and accessibility.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Edit drafts','Check brand consistency','Flag unsupported claims'),'skills',JSON_ARRAY('Editing','Accessibility','Fact checking'),'human_review','Publication'),'published'),
('91000000-0000-4000-8000-000000000024','research-assistant','Research Assistant','Research','Synthesises approved sources with uncertainty and citations.','medium',1,JSON_OBJECT('functions',JSON_ARRAY('Search approved sources','Create evidence summaries','Maintain citations'),'skills',JSON_ARRAY('Research','Source evaluation','Synthesis'),'human_review','Material conclusions'),'published'),
('91000000-0000-4000-8000-000000000025','engineering-assistant','Engineering Assistant','Engineering','Prepares code, tests and documentation in a controlled workflow.','high',1,JSON_OBJECT('functions',JSON_ARRAY('Draft code changes','Generate tests','Prepare technical notes'),'skills',JSON_ARRAY('Software engineering','Testing','Documentation'),'human_review','Every merge and production action'),'published')
ON DUPLICATE KEY UPDATE name=VALUES(name),department=VALUES(department),summary=VALUES(summary),risk_level=VALUES(risk_level),autonomy_level=VALUES(autonomy_level),configuration_json=VALUES(configuration_json),status=VALUES(status),updated_at=UTC_TIMESTAMP();
